#!/bin/bash
yum update -y
sudo amazon-linux-extras install ansible2
mkdir /home/ec2-user/ansible
aws s3 cp --recursive s3://karthik-girraju/ansible /home/ec2-user/ansible
cd /home/ec2-user/ansible
ansible-playbook ./playbook.yml -i ./inventory